name: Anda RPM

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      runsOn:
        required: false
        default: ubuntu-latest
        type: string
      subatomicServer:
        required: false
        default: https://subatomic.fyralabs.com
        type: string
      subatomicRepo:
        required: false
        type: string
      upload:
        required: false
        default: false
        type: boolean
    secrets:
      subatomicToken:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runsOn }}
    container:
      image: fedora:36
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Install mock configs
        run: |
          dnf install -y createrepo_c git gcc curl wget https://lapis.ultramarine-linux.org/kojifiles/packages/mock-core-configs/37.7/3.um36/noarch/mock-core-configs-37.7-3.um36.noarch.rpm
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Anda
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: anda
      - name: Install Subatomic
        run: go install github.com/FyraLabs/subatomic/subatomic-cli@latest
      - name: Build with Anda
        run: anda build ${{ inputs.name }} --package rpm -c ultramarine-37-x86_64
      - name: Pack Non-Uploaded Build
        run: tar -cf anda-build.tar anda-build
        if: ${{ !inputs.upload }}
      - name: Upload Non-Uploaded Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: anda-build-${{ inputs.runsOn }}.tar
          path: anda-build.tar
        if: ${{ !inputs.upload }}
      - name: Upload to Subatomic
        run: subatomic-cli upload --server ${{ inputs.subatomicServer }} --token ${{ secrets.subatomicToken }} ${{ inputs.repo }} anda-build/rpm/rpms/* anda-build/rpm/srpm/*
        if: ${{ inputs.upload }}
